members/urls.py
from django.urls import path
from . import views
from .views import BookSearchView
from .views import MemberSearchView

urlpatterns = [
    path('', views.home, name='home'),
    path('search/', BookSearchView.as_view(), name='book_search'),
    path('member_search/', MemberSearchView.as_view(), name='member_search'),
    path('station_search/', views.station_search, name='station_search'),
    path('member/', views.member_info, name='member_info'),
    path('book/<int:id>', views.book_detail, name='book_detail'),
    path('station/<int:id>', views.station_detail, name='station_detail'),
    path('login/', views.login, name='login'),
    path('login_successful/', views.login_successful, name='login_successful'),
    path('register/', views.register, name='register'),
    path('register_successful/', views.register_successful, name='register_successful'),
    path('logout/', views.logout, name='logout'),
    path('sulogout/', views.superuser_logout, name='superuser_logout'),
    
]

self_service_book/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('members.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Administrator(models.Model):
    # 管理員
    # Model: 名、姓、帳號、密碼
    fname = models.CharField(max_length=20, verbose_name='名')
    lname = models.CharField(max_length=5, verbose_name='姓')
    acc = models.CharField(max_length=30, unique=True, verbose_name='帳號')
    passwd = models.CharField(max_length=30, verbose_name='密碼')

    # 顯示管理員: "名 姓"
    def __str__(self):
        return f"{self.fname} {self.lname}"

class Member(models.Model):
    # 會員
    # Model: 電話、身分證、名、姓、性別
    # 性別選擇
    sex_type = [
        ("M", "男性"),
        ("F", "女性"),
    ]
    phone = models.CharField(max_length=10, unique=True, verbose_name='電話')
    ssn = models.CharField(max_length=10, unique=True, verbose_name='身分證')
    fname = models.CharField(max_length=20, verbose_name='名')
    lname = models.CharField(max_length=5, verbose_name='姓')
    sex = models.CharField(max_length=1, choices=sex_type, null=True, verbose_name='性別')


    # 連結user
    user = models.OneToOneField(User, on_delete=models.CASCADE, default= None, blank=True, null=True)

    def __str__(self):
        return f"{self.fname} {self.lname}"

class Station(models.Model):
    # 站點
    # Model: 地址、站名、狀態
    # 狀態選擇
    statu_type = [
        ("0", "維修中"),
        ("1", "營運中"),
    ]
    addr = models.CharField(max_length=40, unique=True, verbose_name='地址')
    name = models.CharField(max_length=10, verbose_name='站名')
    statu = models.CharField(max_length=1, choices=statu_type, verbose_name='狀態')

    def __str__(self):
        return self.name

class Author(models.Model):
    # 作者
    # Model: 名、姓
    fname = models.CharField(max_length=20, verbose_name='名')
    lname = models.CharField(max_length=5, verbose_name='姓')

    class Meta:
        unique_together = ('fname', 'lname')    

    def __str__(self):
        # 顯示作者: "名 姓"
        return f"{self.fname} {self.lname}"

class Publisher(models.Model):
    # 出版社
    # Model: 出版社名稱
    name = models.CharField(max_length=20, unique=True, verbose_name='出版社名稱')

    def __str__(self):
        return self.name

class Book(models.Model):
    # 書籍
    # Model: 書名、ISBN、作者、出版社、書本封面、狀態、目前借閱會員、目前所在站點(後二依狀態判定)
    # 狀態選擇
    statu_type = [
        ("0", "站內"),
        ("1", "借出"),
    ]
    title = models.CharField(max_length=25, verbose_name='書名')
    isbn = models.CharField(max_length=13, unique=True, verbose_name='ISBN')
    # 作者可以用多值
    author = models.ManyToManyField(Author, related_name='books', verbose_name='作者')
    publisher = models.ForeignKey(Publisher, on_delete=models.CASCADE, related_name='books', verbose_name='出版社')
    img = models.ImageField(upload_to='book_images/', null=True, verbose_name='書本封面')
    statu = models.CharField(max_length=1, choices=statu_type, default="0", verbose_name='狀態')
    # 依statu判斷查看/更改會員或站點
    member = models.ForeignKey(Member, on_delete=models.CASCADE, null=True, blank=True, related_name='books', verbose_name='會員')
    station = models.ForeignKey(Station, on_delete=models.CASCADE, null=True, blank=True, related_name='books', verbose_name='站點')

    def __str__(self):
        return self.title

members/forms.py
from django import forms

class BookSearchForm(forms.Form):
    SEARCH_CHOICES = [
        ('title', '書名'),
        ('isbn', 'ISBN'),
        ('lname', '姓'),
        ('fname', '名'),
        ('publisher', '出版社'),
    ]
    search_by = forms.MultipleChoiceField(choices=SEARCH_CHOICES, widget=forms.CheckboxSelectMultiple, required=False)
    query = forms.CharField(max_length=25, required=False)

class MemberSearchForm(forms.Form):
    SEARCH_CHOICES = [
        ('mssn', '身分證'),
        ('mlname', '姓'),
        ('mfname', '名'),
        ('mphone', '電話'),
    ]
    search_by = forms.MultipleChoiceField(choices=SEARCH_CHOICES, widget=forms.CheckboxSelectMultiple, required=False)
    query = forms.CharField(max_length=25, required=False)

members/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.http import HttpResponse
from django.template import loader
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .models import Administrator, Member, Station, Author, Publisher, Book
from .forms import BookSearchForm
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

def home(request):
    form = BookSearchForm()
    books = Book.objects.all()
    member = None
    if request.user.is_authenticated:
        try:
            member = Member.objects.get(user=request.user)
        except Member.DoesNotExist:
            pass
    context = {
        'form': form,
        'books': books,
        'member': member,
    }
    return render(request, 'homepage.html', context)

def superuser_logout(request):
    auth_logout(request)
    return redirect('home')

class BookSearchView(ListView):
    model = Book
    template_name = 'book_search.html'
    context_object_name = 'books'

    def get_queryset(self):
        queryset = Book.objects.all()

        title_query = self.request.GET.get('title_query')
        isbn_query = self.request.GET.get('isbn_query')
        lname_query = self.request.GET.get('lname_query')
        fname_query = self.request.GET.get('fname_query')
        publisher_query = self.request.GET.get('publisher_query')

        if title_query and 'search_by_title' in self.request.GET:
            queryset = queryset.filter(title__icontains=title_query)
        if isbn_query and 'search_by_isbn' in self.request.GET:
            queryset = queryset.filter(isbn__icontains=isbn_query)
        if lname_query and 'search_by_lname' in self.request.GET:
            queryset = queryset.filter(author__lname__icontains=lname_query)
        if fname_query and 'search_by_fname' in self.request.GET:
            queryset = queryset.filter(author__fname__icontains=fname_query)
        if publisher_query and 'search_by_publisher' in self.request.GET:
            publisher_query = publisher_query.strip()  # 移除空格
            queryset = queryset.filter(publisher__name__iexact=publisher_query) # 返回與輸入的出版社名稱完全匹配的書籍
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['request'] = self.request
        return context



class MemberSearchView(ListView):
    model = Member
    template_name = 'member_search.html'
    context_object_name = 'members'

    def get_queryset(self):
        queryset = Member.objects.all()

        mssn_query = self.request.GET.get('mssn_query')
        mlname_query = self.request.GET.get('mlname_query')
        mfname_query = self.request.GET.get('mfname_query')
        mphone_query = self.request.GET.get('mphone_query')

        if mssn_query and 'search_by_mssn' in self.request.GET:
            queryset = queryset.filter(ssn__icontains=mssn_query)
        if mlname_query and 'search_by_mlname' in self.request.GET:
            queryset = queryset.filter(lname__icontains=mlname_query)
        if mfname_query and 'search_by_mfname' in self.request.GET:
            queryset = queryset.filter(fname__icontains=mfname_query)
        if mphone_query and 'search_by_mphone' in self.request.GET:
            queryset = queryset.filter(phone__icontains=mphone_query)
        return queryset


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['request'] = self.request
        return context

















def station_search(request):
    location = request.GET.get('station_location')
    if location:
        stations = Station.objects.filter(addr__icontains=location)
    else:
        stations = Station.objects.none()
    return render(request, 'station_search.html', {'stations': stations})

@login_required
def member_info(request):
    if request.user.is_superuser:
            return redirect('home')
    if request.method == "POST":
        id = request.POST.get('book_id')
        return_book = Book.objects.get(id=id)
        return_book.statu = "0"
        return_book.save()
        return redirect('member_info')
    member = Member.objects.get(user=request.user)
    borrowed_books = member.books.filter(statu='1')

    context = {
        'member': member,
        'borrowed_books': borrowed_books,
    }
    return render(request, 'member_info.html', context)

def book_detail(request, id):
    borrow_success = False
    if request.method == "POST":
        if request.user.is_superuser:
            return redirect('book_detail', id=id)
        if not request.user.is_authenticated:
            return redirect('login')
        member = Member.objects.get(user=request.user)
        id = request.POST.get('book_id')
        book = Book.objects.get(id=id)
        book.statu = "1"
        book.member = member
        book.save()
        borrow_success = True
        context = {
            'book': book,
            'borrow_success': borrow_success,
        }
        return render(request, 'book_detail.html', context)
    book = Book.objects.get(id = id)
    context = {
        'book': book,
        'borrow_success': borrow_success,
    }
    return render(request, 'book_detail.html', context)

def station_detail(request, id):
    station = Station.objects.get(id = id)
    books = station.books.filter(statu='0')
    context = {
        'station': station,
        'books': books,
    }
    return render(request, 'station_detail.html', context)


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            auth_login(request, user)
            return redirect('login_successful')
        else:
            messages.error(request, '帳號或密碼錯誤')
    return render(request, 'login.html')

def login_successful(request):
    return render(request, 'login_successful.html')

def register(request):
    if request.method == 'POST':
        fname = request.POST['fname']
        lname = request.POST['lname']
        phone = request.POST['phone']
        ssn = request.POST['ssn']
        sex = request.POST['sex']
        username = request.POST['username']
        password = request.POST['password']
        
        if User.objects.filter(username=username).exists():
            messages.error(request, '帳號已存在，請嘗試其他帳號或登入現有帳號')
            return redirect('login')
        
        if Member.objects.filter(phone=phone).exists():
            messages.error(request, '電話號碼已存在，請嘗試其他電話號碼')
            return redirect('register')
        
        if Member.objects.filter(ssn=ssn).exists():
            messages.error(request, '身分證號碼已存在，請嘗試其他身分證號碼')
            return redirect('register')
        
        user = User.objects.create_user(username=username, password=password)
        user.save()
        new_member = Member(user=user, fname=fname, lname=lname, ssn=ssn, phone=phone, sex=sex)
        new_member.save()
        
        return redirect('register_successful')
    
    return render(request, 'register.html')


def register_successful(request):
    return render(request, 'register_successful.html')

def logout(request):
    auth_logout(request)
    return redirect('home')

members/templates/Mama.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>B&R Book</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/mama.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    {% block loadcss %}{% endblock %}
    <!-- <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}"/> -->

</head>
<body>
    {% load static %}
    <div class="top">
        <h1 style="font-size: 50px;"><a href="/" style="color: rgb(33, 8, 76); text-decoration: none;">B&R Book</a></h1>
        <h3>Self-Service Borrowing and Returning Books.</h3>
    </div>

    <a href="{% url 'member_info' %}">
        {% if request.user.is_superuser %}
            <img class="person" src="https://png.pngtree.com/png-vector/20191022/ourmid/pngtree-hammer-and-wrench-vector-illustration-with-simple-design-isolated-on-white-png-image_1846023.jpg" alt="管理員">
            <p style="color: #f00; position: absolute; top: 75px; right: 10px;">管理員不能使用<br>訪客登入功能!!!</p>
        {% elif request.user.is_authenticated %}
            {% if member and member.sex == 'F' %}
                <img class="person" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQul6cUgguGC_LWW8Vg7mvsBC-pS6LfaVNhW57O3MF352pjci8uO3mvaErbu_3bejzJLLg&usqp=CAU" alt="女會員">
            {% elif member and member.sex == 'M' %}
                <img class="person" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdlU9zjkd_gZqm6RcA70J3W23t4yJGcOhUJ8vSRQiOyEhx3ty5dDb4i0rhuZAhvgH3mgA&usqp=CAU" alt="男會員">
            {% endif %}
        {% else %}
            <img class="person" src="https://photo-static-api.fotomore.com/creative/vcg/400/new/VCG41N1198413935.jpg" alt="訪客頭">
        {% endif %}
    </a>
    <!-- 這邊放右上角頭像，圖案幫找好在css裡了，class="person"-->

    {% block home %}{% endblock%}
    <div class="mid">{% block main %}{% endblock%}</div>


    <div class="bottom">
        <p>R&B Book自助借還書管理系統</p>
        <p>維護員：曾予菲、許尹瑄、詹亦萱、陳螢貞、李宸儀</p>
        <p>沒有聯絡專線，有問題也請不要找我們，謝謝。</p><br>
        {% if request.user.is_superuser %}
            <p><a href="{% url 'superuser_logout' %}">管理員登出</a> | <a href="\admin">進入管理介面</a>|<a href="\">回首頁</a></p>
        {%else%}
            <p><a href="\admin">管理員登入</a>|<a href="\">回首頁</a></p>
        {% endif %}
        

    </div>
    
</body>
</html>

members/templates/book_detail.html
{% extends 'Mama.html' %}

{% block main %}
<h1>書籍資料</h1>
<img src="{{ book.img.url }}" alt="book_img" style="width: 200px;">
<h2>{{ book.title }}</h2>
<p>出版社: {{ book.publisher }}</p>
<p>作者: {{ book.author.all|join:", " }}</p>
<p>狀態: {{ book.get_statu_display }}</p>

<!-- 管理員的部分-->
{% if request.user.is_superuser %}
{% if book.statu == "1" %}
<p>借閱人:{{ book.member }}</p>
{% endif %}
{% endif %}
<!-- --------->

{% if book.statu == "0" %}
<p>所在站點: {{ book.station.name }}</p>
<p>站點位置: {{ book.station.addr }}</p>
<form method="post">
    {% csrf_token %}
    <input type="hidden" name="book_id" value="{{ book.id }}">
    <button type="submit">借書</button>
</form>
{% endif %}

<!-- 借書成功的話跳出成功訊息 -->
{% if borrow_success %}
<script>
    window.onload = function () {
        alert("書籍 '{{ book.title }}' 借閱成功!\n借閱人: {{ book.member }}");
    }
</script>
{% endif %}

<!-- 管理員的部分-->
{% if request.user.is_superuser %}
<p style="color: #f00;">管理員不能借書!!</p>
<p><a href="{% url 'admin:members_book_change' book.id %}">編輯「{{ book.title }} 」此書</a></p>
{% endif %}
<!-- --------->
 <br><br>
{% endblock%}

members/templates/book_search.html
{% extends 'Mama.html' %}

{% block loadcss %}
    <link rel="stylesheet" href="../../static/css/home.css">
{% endblock %}

{% block main %}
<div class="primary">
    <div class="left">
        <h3>書本查詢：</h3>
        <script>
            function sanitizeInput() {
                const fields = ['title_query', 'isbn_query', 'lname_query', 'fname_query', 'publisher_query'];
                fields.forEach(field => {
                    const input = document.getElementById(field);
                    if (input) {
                        input.value = input.value.trim().replace(/\s+/g, ' '); // 去除多餘的空格
                    }
                });
            }

            function validateForm() {
                const checkboxes = [
                    document.getElementById('search_by_title'),
                    document.getElementById('search_by_isbn'),
                    document.getElementById('search_by_lname'),
                    document.getElementById('search_by_fname'),
                    document.getElementById('search_by_publisher')
                ];
                const inputs = [
                    document.getElementById('title_query'),
                    document.getElementById('isbn_query'),
                    document.getElementById('lname_query'),
                    document.getElementById('fname_query'),
                    document.getElementById('publisher_query')
                ];

                const anyChecked = checkboxes.some(checkbox => checkbox.checked);
                const anyInputProvided = inputs.some((input, index) => {
                    return checkboxes[index].checked && input.value.trim() !== '';
                });

                if (!anyChecked) {
                    alert('請勾選查詢種類');
                    return false;
                }

                if (anyChecked && !anyInputProvided) {
                    alert('請輸入查詢資訊');
                    return false;
                }

                sanitizeInput();
                return true;
            }
        </script>
        <form method="get" action="{% url 'book_search' %}" onsubmit="return validateForm()">
            <div>
                <input type="checkbox" id="search_by_title" name="search_by_title">
                <label for="search_by_title">書名</label>
                <input type="text" id="title_query" name="title_query"
                    value="{{ request.GET.title_query|default_if_none:'' }}">
            </div>
            <div>
                <input type="checkbox" id="search_by_isbn" name="search_by_isbn">
                <label for="search_by_isbn">ISBN</label>
                <input type="text" id="isbn_query" name="isbn_query"
                    value="{{ request.GET.isbn_query|default_if_none:'' }}">
            </div>
            <div>
                <input type="checkbox" id="search_by_lname" name="search_by_lname">
                <label for="search_by_lname">姓</label>
                <input type="text" id="lname_query" name="lname_query"
                    value="{{ request.GET.lname_query|default_if_none:'' }}">
            </div>
            <div>
                <input type="checkbox" id="search_by_fname" name="search_by_fname">
                <label for="search_by_fname">名</label>
                <input type="text" id="fname_query" name="fname_query"
                    value="{{ request.GET.fname_query|default_if_none:'' }}">
            </div>
            <div>
                <input type="checkbox" id="search_by_publisher" name="search_by_publisher">
                <label for="search_by_publisher">出版社</label>
                <input type="text" id="publisher_query" name="publisher_query"
                    value="{{ request.GET.publisher_query|default_if_none:'' }}">
            </div>
            <div class="search-box">
                <button type="submit">查詢</button>
            </div>
        </form>
        <br>
        <hr><br>
        <h3>站點查詢：</h3>
        <form method="get" action="{% url 'station_search' %}">
            <div class="search-box-station">
                <label for="station_location">查詢地點</label>
                <select id="station_location" name="station_location">
                    <option value="Taipei">臺北</option>
                    <option value="Taichung">臺中</option>
                </select>
                <button type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </form>
    </div>
    <div class="right">
        {% if books %}
        <h3>搜索結果：</h3>
        {% for book in books %}
        <a href="{% url 'book_detail' book.id %}">
            <img class="book" src="{{ book.img.url }}" alt="{{ book.title }}的封面">
        </a>
        {% endfor %}
        {% else %}
        <p>查無相關書籍</p>
        {% endif %}
    </div>
</div>
{% endblock %}

members/templates/station_search.html
{% extends 'Mama.html' %}

{% block loadcss %}
    <link rel="stylesheet" href="../../static/css/home.css">
{% endblock %}

{% block main %}
<div class="primary">
    <div class="left">
        <h3>書本查詢：</h3>
        <script>
            function sanitizeInput() {
                const fields = ['title_query', 'isbn_query', 'lname_query', 'fname_query', 'publisher_query'];
                fields.forEach(field => {
                    const input = document.getElementById(field);
                    if (input) {
                        input.value = input.value.trim().replace(/\s+/g, ' '); // 去除多餘的空格
                    }
                });
            }

            function validateForm() {
                const checkboxes = [
                    document.getElementById('search_by_title'),
                        document.getElementById('search_by_isbn'),
                        document.getElementById('search_by_lname'),
                        document.getElementById('search_by_fname'),
                        document.getElementById('search_by_publisher'),
                        document.getElementById('search_by_ssn'),
                        document.getElementById('search_by_lname'),
                        document.getElementById('search_by_fname'),
                        document.getElementById('search_by_phone')
                    ];
                    const inputs = [
                    document.getElementById('title_query'),
                        document.getElementById('isbn_query'),
                        document.getElementById('lname_query'),
                        document.getElementById('fname_query'),
                        document.getElementById('publisher_query'),
                        document.getElementById('ssn_query'),
                        document.getElementById('lname_query'),
                        document.getElementById('fname_query'),
                        document.getElementById('phone_query')
                    ];

                const anyChecked = checkboxes.some(checkbox => checkbox.checked);
                const anyInputProvided = inputs.some((input, index) => {
                    return checkboxes[index].checked && input.value.trim() !== '';
                });

                if (!anyChecked) {
                    alert('請勾選查詢種類');
                    return false;
                }

                if (anyChecked && !anyInputProvided) {
                    alert('請輸入查詢資訊');
                    return false;
                }

                sanitizeInput();
                return true;
            }
        </script>
        <form method="get" action="{% url 'book_search' %}" onsubmit="return validateForm()">
            <div>
                <input type="checkbox" id="search_by_title" name="search_by_title">
                <label for="search_by_title">書名</label>
                <input type="text" id="title_query" name="title_query"
                    value="{{ request.GET.title_query|default_if_none:'' }}">
            </div>
            <div>
                <input type="checkbox" id="search_by_isbn" name="search_by_isbn">
                <label for="search_by_isbn">ISBN</label>
                <input type="text" id="isbn_query" name="isbn_query"
                    value="{{ request.GET.isbn_query|default_if_none:'' }}">
            </div>
            <div>
                <input type="checkbox" id="search_by_lname" name="search_by_lname">
                <label for="search_by_lname">作者姓</label>
                <input type="text" id="lname_query" name="lname_query"
                    value="{{ request.GET.lname_query|default_if_none:'' }}">
            </div>
            <div>
                <input type="checkbox" id="search_by_fname" name="search_by_fname">
                <label for="search_by_fname">作者名</label>
                <input type="text" id="fname_query" name="fname_query"
                    value="{{ request.GET.fname_query|default_if_none:'' }}">
            </div>
            <div>
                <input type="checkbox" id="search_by_publisher" name="search_by_publisher">
                <label for="search_by_publisher">出版社(完整名稱)</label>
                <input type="text" id="publisher_query" name="publisher_query"
                    value="{{ request.GET.publisher_query|default_if_none:'' }}">
            </div>
            <div class="search-box">
                <button type="submit">查詢</button>
            </div>
        </form>
        <br>
        <hr><br>
        <h3>站點查詢：</h3>
        <form method="get" action="{% url 'station_search' %}">
            <div class="search-box-station">
                <label for="station_location">查詢地點</label>
                <select id="station_location" name="station_location">
                    <option value="Taipei">臺北</option>
                    <option value="Taichung">臺中</option>
                </select>
                <button type="submit">
                    <i class="fa fa-search"></i>
                </button>
            </div>
        </form>
        <br><hr>
            
        {% if request.user.is_superuser %}    
        <h3>會員查詢：</h3>
            <script>
                function sanitizeInput() {
                    const fields = ['mssn_query','mlname_query', 'mfname_query', 'mphone_query'];
                    fields.forEach(field => {
                        const input = document.getElementById(field);
                        if (input) {
                            input.value = input.value.trim().replace(/\s+/g, ' '); // 去除多餘的空格
                        }
                    });
                }
    
                function validateForm() {
                    const checkboxes = [
                    document.getElementById('search_by_title'),
                        document.getElementById('search_by_isbn'),
                        document.getElementById('search_by_lname'),
                        document.getElementById('search_by_fname'),
                        document.getElementById('search_by_publisher'),
                        document.getElementById('search_by_mssn'),
                        document.getElementById('search_by_mlname'),
                        document.getElementById('search_by_mfname'),
                        document.getElementById('search_by_mphone')
                    ];
                    const inputs = [
                    document.getElementById('title_query'),
                        document.getElementById('isbn_query'),
                        document.getElementById('lname_query'),
                        document.getElementById('fname_query'),
                        document.getElementById('publisher_query'),
                        document.getElementById('mssn_query'),
                        document.getElementById('mlname_query'),
                        document.getElementById('mfname_query'),
                        document.getElementById('mphone_query')
                    ];
    
                    const anyChecked = checkboxes.some(checkbox => checkbox.checked);
                    const anyInputProvided = inputs.some((input, index) => {
                        return checkboxes[index].checked && input.value.trim() !== '';
                    });
    
                    if (!anyChecked) {
                        alert('請勾選查詢種類');
                        return false;
                    }
    
                    if (anyChecked && !anyInputProvided) {
                        alert('請輸入查詢資訊');
                        return false;
                    }
    
                    sanitizeInput();
                    return true;
                }
            </script>
            <form method="get" action="{% url 'member_search' %}" onsubmit="return validateForm()">
                <div>
                    <input type="checkbox" id="search_by_mssn" name="search_by_mssn">
                    <label for="search_by_mssn">身分證</label>
                    <input type="text" id="mssn_query" name="mssn_query"
                        value="{{ request.GET.mssn_query|default_if_none:'' }}">
                </div>
                <div>
                    <input type="checkbox" id="search_by_mlname" name="search_by_mlname">
                    <label for="search_by_mlname">姓</label>
                    <input type="text" id="mlname_query" name="mlname_query"
                        value="{{ request.GET.mlname_query|default_if_none:'' }}">
                </div>
                <div>
                    <input type="checkbox" id="search_by_mfname" name="search_by_mfname">
                    <label for="search_by_mfname">名</label>
                    <input type="text" id="mfname_query" name="mfname_query"
                        value="{{ request.GET.mfname_query|default_if_none:'' }}">
                </div>
                <div>
                    <input type="checkbox" id="search_by_mphone" name="search_by_mphone">
                    <label for="search_by_mphone">電話</label>
                    <input type="text" id="mphone_query" name="mphone_query"
                        value="{{ request.GET.mphone_query|default_if_none:'' }}">
                </div>
                <div class="search-box">
                    <button type="submit">查詢</button>
                </div>
            </form>
        {% endif %}

    </div>
    <div class="right">
        {% if stations %}
        <h3>站點搜索結果：</h3>
        <table class="station-table">
            <thead>
                <tr>
                    <th>站名</th>
                    <th>狀態</th>
                    <th>地址</th>
                </tr>
            </thead>
            <tbody>
                {% for station in stations %}
                <tr>
                    <td><a href="{% url 'station_detail' station.id %}">{{ station.name }}</a></td>
                    <td class="status-{{ station.statu }}">{{ station.get_statu_display }}</td>
                    <td>{{ station.addr }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <p>查無站點</p>
        {% endif %}
    </div>
</div>
{% endblock %}